---
title: "Berkshire's Performance vs. the S&P 500"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ezplot)
library(tidyr)
library(plotly)
library(flexdashboard)
```

Column {.sidebar}
-----------------------------------------------------------------------
The S&P 500 numbers are **pre-tax** whereas the Berkshire numbers are **after-tax**.

Compounded Annual Gain (1965-2016):

* Berkshire: **20.8%**
* S&P 500: &emsp; 9.7%

Overall Gain (1964-2016):

* Berkshire: **1,972,595%**
* S&P 500: &emsp;&emsp; 12,717%

Data source: Warren Buffett's [2016 annual letter](http://www.berkshirehathaway.com/letters/2016ltr.pdf).

Made by [Cabaceo LLC](https://cabaceo.com).


Column
-----------------------------------------------------------------------

### Berkshire's Performance vs. the S&P 500

```{r}
# data prep
yr = 1965:2016 
berkshire = c(49.5, -3.4, 13.3, 77.8, 19.4, -4.6, 80.5, 8.1, -2.5, -48.7,
              2.5, 129.3, 46.8, 14.5, 102.5, 32.8, 31.8, 38.4, 69, -2.7, 
              93.7, 14.2, 4.6, 59.3, 84.6, -23.1, 35.6, 29.8, 38.9, 25, 57.4, 
              6.2, 34.9, 52.2, -19.9, 26.6, 6.5, -3.8, 15.8, 4.3, 0.8, 24.1, 
              28.7, -31.8, 2.7, 21.4, -4.7, 16.8, 32.7, 27, -12.5, 23.4)
sp500 = c(10, -11.7, 30.9, 11, -8.4, 3.9, 14.6, 18.9, -14.8, -26.4, 37.2, 23.6,
          -7.4, 6.4, 18.2, 32.3, -5, 21.4, 22.4, 6.1, 31.6, 18.6, 5.1, 16.6, 
          31.7, -3.1, 30.5, 7.6, 10.1, 1.3, 37.6, 23, 33.4, 28.6, 21, -9.1, -11.9,
          -22.1, 28.7, 10.9, 4.9, 15.8, 5.5, -37, 26.5, 15.1, 2.1, 16, 32.4, 13.7,
          1.4, 12)
df = data.frame(yr, berkshire, sp500)

# plot
plot_ly(df, x = ~yr, y = ~sp500, type = 'bar', 
        name = 'in S&P 500 with Dividends Included',
        marker = list(color = 'rgb(55, 83, 109)')) %>%
  add_trace(y = ~berkshire, name = 'in Per-Share Market Value of Berkshire',
            marker = list(color = 'rgb(26, 118, 255)')) %>%
  layout(title = "Berkshire's Performance vs. the S&P 500",
         xaxis = list(title = "",
                      tickfont = list(size = 14, color = 'rgb(107, 107, 107)')
                      ),
         yaxis = list(title = 'Annual Percent Change',
                      titlefont = list(size = 16, color = 'rgb(107, 107, 107)'),
                      tickfont = list(size = 14, color = 'rgb(107, 107, 107)')
                      ),
         legend = list(x = 0, y = 1, bgcolor = 'rgba(255, 255, 255, 0)', 
                       bordercolor = 'rgba(255, 255, 255, 0)'),
         barmode = 'group')
```
